BoVoyage.WEB/Controllers/AuthentificationController.cs
using BoVoyage.BUSINESS.Services;
using BoVoyage.COMMON.Extensions;
using BoVoyage.DAL.Data;
using BoVoyage.WEB.Controllers.Base;
using BoVoyage.WEB.Filters;
using BoVoyage.WEB.Models;
using BoVoyage.WEB.Tools;
using System.Web.Mvc;

namespace BoVoyage.WEB.Controllers
{
	public class AuthentificationController : BaseController
	{
		private readonly ServiceCustomer serviceCustomer;

		public AuthentificationController()
		{
			this.serviceCustomer = new ServiceCustomer(new DbDataAuthentification(), new DbDataCustomer());
		}

		// POST: Authentification/Create
		[HttpPost]
		// [ValidateAntiForgeryToken]
		public ActionResult Login(AuthenticationLoginViewModel model)
		{
			if (ModelState.IsValid)
			{
				var hash = model.Password.GenerateSHA512String();
				var customer = this.serviceCustomer.GetCustomersWithAuthentificationInclude(model.Mail, hash);

				if (customer == null)
				{
					Display("Login / mot de passe invalide", MessageType.ERROR);
					return RedirectToAction("index", "home");
				}
				else
				{
					CustomerViewModel customerViewModel = TransformModelCustomer.CustomerToModelView(customer);
					Session["CUSTOMER"] = customerViewModel;

					if (TempData["REDIRECT"] != null)
						return Redirect(TempData["REDIRECT"].ToString());
					else
						return RedirectToAction("index", "home");
				}
			}
			return RedirectToAction("index", "home");
		}

		[Authentication(Type = "CUSTOMER")]
		public ActionResult Logout()
		{
			Session.Remove("CUSTOMER");
			return RedirectToAction("index", "home");
		}

		// GET: Authentification/Edit/5
		public ActionResult Edit(int id)
		{
			return View();
		}

		// POST: Authentification/Edit/5
		[HttpPost]
		public ActionResult Edit(int id, FormCollection collection)
		{
			try
			{
				// TODO: Add update logic here

				return RedirectToAction("Index");
			}
			catch
			{
				return View();
			}
		}

		// GET: Authentification/Delete/5
		public ActionResult Delete(int id)
		{
			return View();
		}

		// POST: Authentification/Delete/5
		[HttpPost]
		public ActionResult Delete(int id, FormCollection collection)
		{
			try
			{
				// TODO: Add delete logic here

				return RedirectToAction("Index");
			}
			catch
			{
				return View();
			}
		}
	}
}

BoVoyage.WEB/Controllers/CustomersController.cs
using BoVoyage.BUSINESS.Services;
using BoVoyage.COMMON.Extensions;
using BoVoyage.DAL.Data;
using BoVoyage.WEB.Controllers.Base;
using BoVoyage.WEB.Filters;
using BoVoyage.WEB.Models;
using BoVoyage.WEB.Tools;
using System.Web.Mvc;

namespace BoVoyage.WEB.Controllers
{
	public class CustomersController : BaseController
	{
		private readonly ServiceCustomer serviceCustomer;
		private readonly ServiceBookingFile serviceBookingFile;

		public CustomersController()
		{
			this.serviceCustomer = new ServiceCustomer(new DbDataAuthentification(), new DbDataCustomer());
			this.serviceBookingFile = new ServiceBookingFile(new DbDataBookingFile());
		}

		// GET: Customers/Create
		public ActionResult Subscribe()
		{
			return View();
		}

		// POST: Customers/Create
		[HttpPost]
		public ActionResult Subscribe([Bind(Exclude = "ID, AuthentificationID")] CustomerViewModel model)
		{
			try
			{
				if (ModelState.IsValid)
				{
					var customer = TransformModelCustomer.CustomerModelViewToModel(model);
					customer.Authentification.Password = customer.Authentification.Password.GenerateSHA512String();

					this.serviceCustomer.AddCustomer(customer.Authentification, customer);

					Display("L'enregistrement est un succès");
					return RedirectToAction("Index", "Home");
				}
				else
				{
					return View(model);
				}
				// TODO: Add insert logic here
			}
			catch
			{
				Display("Erreur !", MessageType.ERROR);
				return View();
			}
		}

		// GET: Customers/Details/5
		[Authentication(Type = "CUSTOMER")]
		public ActionResult Details()
		{
			CustomerViewModel customerViewModel = (CustomerViewModel)Session["CUSTOMER"];
			return View(customerViewModel);
		}

		// GET: Customers/Edit/5
		[Authentication(Type = "CUSTOMER")]
		public ActionResult Edit(int id)
		{
			var customer = (CustomerViewModel)Session["CUSTOMER"];
			if (customer.ID != id)
				return HttpNotFound();
			CustomerViewModel customerViewModel = customer;
			return View(customerViewModel);
		}

		// POST: Customers/Edit/5
		[HttpPost]
		[Authentication(Type = "CUSTOMER")]
		public ActionResult Edit(int id, CustomerViewModel model)
		{
			try
			{
				if (model == null || id != model.ID)
					return HttpNotFound();
				// TODO: Add update logic here

				if (ModelState.IsValid)
				{
					var customer = this.serviceCustomer.GetCustomerWithAuthentificationInclude(id);
					customer.Civility = model.Civility;
					customer.FirstName = model.FirstName;
					customer.LastName = model.LastName;
					customer.BirthDate = model.BirthDate;
					customer.Address = model.Address;
					customer.PhoneNumber = model.PhoneNumber;
					customer.Authentification.Password = model.Password;
					customer.Authentification.Password = model.Email;

					this.serviceCustomer.UpdateCustomer(customer);

					CustomerViewModel customerViewModel = TransformModelCustomer.CustomerToModelView(customer);
					Session["CUSTOMER"] = customerViewModel;
					Display("Les changements sont bien enregistrés");
					return RedirectToAction("details");
				}
				else
				{
					return View(model);
				}
			}
			catch
			{
				Display("Erreur !", MessageType.ERROR);
				return View();
			}
		}

		// GET: Customers/Create
		[Authentication(Type = "CUSTOMER")]
		public ActionResult Reservation()
		{
			CustomerViewModel customerViewModel = (CustomerViewModel)Session["CUSTOMER"];
			ViewBag.List = this.serviceBookingFile.GetAllBookingFilesWithTravelsAndDestinationsIncluded(customerViewModel.ID);
			return View();
		}
	}
}

BoVoyage.WEB/Controllers/DestinationsController.cs
using BoVoyage.BUSINESS.Services;
using BoVoyage.DAL.Data;
using BoVoyage.DAL.Entites;
using BoVoyage.WEB.Controllers.Base;
using BoVoyage.WEB.Models;
using BoVoyage.WEB.Tools;
using System.Web.Mvc;

namespace BoVoyage.WEB.Controllers
{
	public class DestinationsController : BaseController
	{
		private readonly ServiceDestination serviceDestination;

		public DestinationsController()
		{
			this.serviceDestination = new ServiceDestination(new DbDataDestination());
		}

		// GET: Destinations

		public ActionResult Index()
		{
			var destination = serviceDestination.GetAllDestinationsWithTravelsNotNull();

			var destinationViewModel = TransformModelDestination.DestinationToModelView(destination);

			return View(destinationViewModel);
		}

		// GET: Destinations/Details/5
		public ActionResult Details(int id)
		{
			Destination destination = this.serviceDestination.GetDestinationWithTravelsIncluded(id);
			if (destination == null)
				return HttpNotFound();

			DestinationViewModel destinationViewModel = TransformModelDestination.DestinationToModelView(destination);

			return View(destinationViewModel);
		}

		// GET: Destinations/Create
		public ActionResult Create()
		{
			return View();
		}

		// POST: Destinations/Create
		[HttpPost]
		public ActionResult Create(FormCollection collection)
		{
			try
			{
				// TODO: Add insert logic here

				return RedirectToAction("Index");
			}
			catch
			{
				return View();
			}
		}

		// GET: Destinations/Edit/5
		public ActionResult Edit(int id)
		{
			return View();
		}

		// POST: Destinations/Edit/5
		[HttpPost]
		public ActionResult Edit(int id, FormCollection collection)
		{
			try
			{
				// TODO: Add update logic here

				return RedirectToAction("Index");
			}
			catch
			{
				return View();
			}
		}

		// GET: Destinations/Delete/5
		public ActionResult Delete(int id)
		{
			return View();
		}

		// POST: Destinations/Delete/5
		[HttpPost]
		public ActionResult Delete(int id, FormCollection collection)
		{
			try
			{
				// TODO: Add delete logic here

				return RedirectToAction("Index");
			}
			catch
			{
				return View();
			}
		}
	}
}

BoVoyage.WEB/Views/Shared/_Layout.cshtml
@{
	var customer = Session["CUSTOMER"] as BoVoyage.WEB.Models.CustomerViewModel;
	//var backofficer = Session["BACKOFFICER"] as BoVoyage.WEB.Models.AuthenticationLoginViewModel; // Fx pour faire apparaitre le menu du backoffice à verifirer
}

@{
	Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title>BoVoyage | @ViewBag.Title</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    @Styles.Render("~/Content/bootstrap")
    @Styles.Render("~/Content/bootstrap-theme")
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="~/Scripts/CookieBar.css" rel="stylesheet" />
    @Styles.Render("~/Content/site")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="icon" href="~/Content/Images/flagSite.png" />
    @*<style>
        body {
            position: relative;
        }

		.affix {
			top: 0;
			width: 100%;
			z-index: 9999 !important;
		}

		.navbar {
			margin-bottom: 0px;
		}

		.affix ~ .container-fluid {
			position: relative;
			top: 50px;
		}

		#section1 {
			padding-top: 50px;
			height: 500px;
			color: #fff;
			background-color: #1E88E5;
		}

		#section2 {
			padding-top: 50px;
			height: 500px;
			color: #fff;
			background-color: #673ab7;
		}

		#section3 {
			padding-top: 50px;
			height: 500px;
			color: #fff;
			background-color: #ff9800;
		}

		#section41 {
			padding-top: 50px;
			height: 500px;
			color: #fff;
			background-color: #00bcd4;
		}

        #section42 {
            padding-top: 50px;
            height: 500px;
            color: #fff;
            background-color: #009688;
        }
    </style>*@
</head>

<body class="w3-light-grey" data-spy="scroll" data-target=".navbar" data-offset="20">

    @*// TODO ramener le footer en arriere plan pour affichage correct du contentBox, retravailler le menu une fois reduit, ainsi que le contentBox*@
    <!-- Navigation Bar -->
    <nav data-spy="affix" data-offset-top="167">
        <div class="container-fluid">
            <div class="navbar-header w3-light-grey w3-opacity w3-hover-opacity-off">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar w3-black"></span>
                    <span class="icon-bar w3-black"></span>
                    <span class="icon-bar w3-black"></span>
                </button>
                <a href="@Url.Action("index", "home")" class="w3-bar-item w3-button w3-text-red w3-hover-red"><b><i class="fa fa-plane w3-margin-right"></i>BoVoyage</b></a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="@Url.Action("index", "Destinations", new { area="" })" class="w3-bar-item w3-button w3-text-red w3-hover-red"><b><i class="fa w3-margin-right"></i>Nos Destinations</b></a>
                    </li>
                    <li>
                        @if (customer == null)
                        {
                            <form class="navbar-form navbar-right" method="post" action="@Url.Action("login", "Authentification")">
                                @Html.AntiForgeryToken()
                                <div class="form-group">
                                    <input type="text" name="mail" class="form-control" placeholder="Login">
                                    <input type="password" name="password" class="form-control" placeholder="Mot de passe" />
                                </div>
                                <button type="submit" class="btn btn-info">OK</button>
                            </form>
                            <ul class="nav navbar-nav navbar-right">
                                <li><a href="@Url.Action("subscribe", "Customers")"><span class="glyphicon glyphicon-user"></span> Inscription</a></li>
                            </ul>
                        }
                        else
                        {
                            <ul class="nav navbar-nav navbar-right">
                                <li><a href="#">Bonjour @customer.LastName</a></li>
                                <li class="w3-dropdown-hover">
                                    <button class="w3-button">Gestion compte</button>
                                    <div class="w3-dropdown-content w3-bar-block w3-card-4">
                                        @*<a href="@Url.Action("Reservation", "Customers")" class="w3-bar-item w3-button">Vos réservations</a>*@
                                        <a href="@Url.Action("Details", "Customers")" class="w3-bar-item w3-button">Votre profil</a>
                                    </div>
                                </li>

								<li><a href="@Url.Action("logout", "Authentification")"><i class="glyphicon glyphicon-log-out"></i></a></li>
							</ul>

                        }
                        @*// Pour afficher les liens dans la bar nav lorsqu'il s'agit d'un backofficer/commercial'
                            @if (backofficer != null)
                            {
                                <a href="@Url.Action("index", "dashboard", new { area="backoffice" })" class="w3-bar-item w3-button w3-right w3-hover-blue w3-text-grey">BackOffice</a>
                            }*@
                    </li>
                </ul>

                @*// Login icon*@
                @*<ul class="nav navbar-nav navbar-right">
                        <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                        <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                    </ul>*@
            </div>
        </div>
    </nav>

	@Html.Partial("_PartialDisplayMessage")

	@*// TODO ancienne navbar*@
	@*<nav data-spy="affix" data-offset-top="167">

            <div class="w3-bar w3-light-grey w3-mlarge w3-opacity w3-hover-opacity-off container-fluid">
                <a href="@Url.Action("index", "home")" class="w3-bar-item w3-button w3-text-red w3-hover-red"><b><i class="fa fa-plane w3-margin-right"></i>BoVoyage</b></a>
                <a href="@Url.Action("index", "Destinations", new { area="" })" class="w3-bar-item w3-button w3-text-red w3-hover-red"><b><i class="fa w3-margin-right"></i>Nos Destinations</b></a>

                @if (customer == null)
                {
                    <form class="navbar-form navbar-right" method="post" action="@Url.Action("login", "Authentification")">
                        @Html.AntiForgeryToken()
                        <div class="form-group">
                            <input type="text" name="mail" class="form-control" placeholder="Login">
                            <input type="password" name="password" class="form-control" placeholder="Mot de passe" />
                        </div>
                        <button type="submit" class="btn btn-info">OK</button>
                    </form>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="@Url.Action("subscribe", "Customers")">Inscription</a></li>
                    </ul>
                }
                else
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="#">Bonjour @customer.LastName</a></li>
                        <li class="w3-dropdown-hover">
                            <button class="w3-button">Gestion compte</button>
                            <div class="w3-dropdown-content w3-bar-block w3-card-4">
                                <a href="@Url.Action("Reservation", "Customers")" class="w3-bar-item w3-button">Vos réservations</a>
                                <a href="@Url.Action("Details", "Customers")" class="w3-bar-item w3-button">Votre profil</a>
                            </div>
                        </li>

                        <li><a href="@Url.Action("logout", "Authentification")"><i class="glyphicon glyphicon-log-out"></i></a></li>
                    </ul>

                }

                @if (backofficer != null)
                {
                    <a href="@Url.Action("index", "dashboard", new { area="backoffice" })" class="w3-bar-item w3-button w3-right w3-hover-blue w3-text-grey">BackOffice</a>
                }
            </div>
        </nav>*@

    <!-- Header -->

    <header class="w3-display-container w3-content" style="max-width:1500px">
        <img class="w3-image img-responsive" src="~/Content/Images/maldives.jpg" alt="London" width="1500" height="700">
        <div class="w3-display-middle" style="width:65%">

			<!-- ContentBox title -->
			<div class="w3-bar w3-black">
				<div class="w3-bar-item w3-red">
					<i class="fa fa-plane w3-margin-right"></i>@ViewBag.Title
				</div>
			</div>

            <!-- ContentBox -->
            <div id="Flight" class="w3-white w3-opacity w3-card w3-hover-opacity-off" style="display:flex">
                <div class="w3-content w3-margin">
                    @RenderSection("ContentBox", required: false)
                </div>
            </div>
        </div>
    </header>

	<!-- Page content -->
	<div class="w3-content" style="max-width:1100px;">
		@RenderBody()

		<!-- Good offers -->
		@RenderSection("GoodOffers", required: false)

		<!-- Explore Nature -->
		@RenderSection("SoonOffers", required: false)

		<!-- Newsletter -->
		@RenderSection("Newsletter", required: false)

		<!-- Personal mail booking -->
		@RenderSection("MailBooking", required: false)

		<!-- End page content -->
	</div>

    <!-- Footer -->
    <div class="w3-container">
        <footer class="w3-container w3-center w3-opacity w3-margin-bottom w3-black">
            <h5>Retrouvez-nous sur</h5>
            <div class="w3-xlarge w3-padding-16">
                <i class="fa fa-facebook-official w3-hover-opacity"></i>
                <i class="fa fa-instagram w3-hover-opacity"></i>
                <i class="fa fa-snapchat w3-hover-opacity"></i>
                <i class="fa fa-pinterest-p w3-hover-opacity"></i>
                <i class="fa fa-twitter w3-hover-opacity"></i>
                <i class="fa fa-linkedin w3-hover-opacity"></i>
            </div>

			<a href="@Url.Action("faq", "home")" class="w3-bar-item w3-button w3-text-red" title="FAQ">FAQ</a>
			<a href="@Url.Action("CGV", "home")" class="w3-bar-item w3-button w3-text-red" title="CG">Condition Générales de Vente</a>
			<a href="@Url.Action("Mentions", "home")" class="w3-bar-item w3-button w3-text-red" title="Legacy">Mentions Légales</a>
			<a href="@Url.Action("contact", "home")" class="w3-bar-item w3-button w3-text-red" title="Contact">Contact</a>
			<a href="@Url.Action("about", "home")" class="w3-bar-item w3-button w3-text-red" title="About">A-propos</a>

			<p>&copy; BoVoyage @DateTime.Now.Year</p>
		</footer>
	</div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/cldr.js"></script>
    <script src="~/Scripts/globalize.js"></script>
    <script src="~/Scripts/jquery.validate.globalize.js"></script>
    <script>
        // Tabs
        function openLink(evt, linkName) {
            var i, x, tablinks;
            x = document.getElementsByClassName("myLink");
            for (i = 0; i < x.length; i++) {
                x[i].style.display = "none";
            }
            tablinks = document.getElementsByClassName("tablink");
            for (i = 0; i < x.length; i++) {
                tablinks[i].className = tablinks[i].className.replace(" w3-red", "");
            }
            document.getElementById(linkName).style.display = "block";
            evt.currentTarget.className += " w3-red";
        }
        // Click on the first tablink on load
        document.getElementsByClassName("tablink")[0].click();

        
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>

BoVoyage.WEB/Views/Shared/_LayoutForm.cshtml
@{
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading">@RenderSection("PanelTitle", true)</div>
    <div class="panel-body">@RenderSection("PanelBody", true)</div>
</div>

@section Scripts
{
	@RenderSection("Scripts", true)
}

BoVoyage.WEB/Views/Shared/_PartialDisplayMessage.cshtml
@using BoVoyage.WEB.Tools;
@{
    /**/

    Message message = TempData["MESSAGE"] as Message;
}


    @if (message != null)
    {
        <p class="alert alert-@message.MessageType">@message.Text</p>
    }
    